name: Format and Lint

on:
  pull_request:
    branches: [main, develop]

jobs:
  format-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Format code
        run: |
          echo "Formatting source code..."
          ruff format src
          echo "Formatting test code..."
          ruff format test

      - name: Check formatting
        run: |
          echo "Checking source code formatting..."
          ruff format --check src
          echo "Checking test code formatting..."
          ruff format --check test

      - name: Lint code
        run: |
          echo "Linting source code..."
          ruff check src
          echo "Linting test code..."
          ruff check test

      - name: Check for formatting changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "::error::Code formatting changes detected. Please run 'ruff format' locally and commit the changes."
            git diff
            exit 1
          else
            echo "No formatting changes detected."
          fi
